server:
  servlet:
    context-path: /notification
  port: 8090
spring:
  cache:
    type: redis
  mail:
    host: smtp.gmail.com
    port: 587
    username: amaklov2002@gmail.com
    password: snjw kuyd szce boqf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: security-jwt
  kafka-topic:
    simple-notification: simple-notification-topic
