spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: security-jwt
  kafka-topic:
    simple-notification: simple-notification-topic
  liquibase:
    enabled: true
  r2dbc:
    url: jdbc:postgresql://localhost:5432/spring-jwt
    username: root
    password: root
server:
  port: 8081
