spring:
  liquibase:
    enabled: true
  kafka-topic:
    simple-notification: simple-notification-topic
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring-jwt
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082